<?php

namespace Scor\CommonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CaducidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaducidadRepository extends EntityRepository
{
}
