conducir:
    pattern: /carnet-conducir
    defaults: { _controller: FrontendBundle:Licencia:conducir }

armas:
    pattern: /permiso-armas
    defaults: { _controller: FrontendBundle:Licencia:armas }

seguridad:
    pattern: /seguridad-privada
    defaults: { _controller: FrontendBundle:Licencia:seguridad }

animales:
    pattern: /animales-peligrosos
    defaults: { _controller: FrontendBundle:Licencia:animales }

nautica:
    pattern: /nautica
    defaults: { _controller: FrontendBundle:Licencia:nautica }

gruas:
    pattern: /gruas
    defaults: { _controller: FrontendBundle:Licencia:gruas }
