parameters:
#    frontend.example.class: Scor\FrontendBundle\Example

services:
    scor.twig.controller_action_extension:
        class: Scor\CommonBundle\Twig\Extension\ControllerActionExtension
        calls:
            - [setRequest, ["@?request="]]
        tags:
            - { name: twig.extension }