parameters:
#    app.example.class: Scor\AppBundle\Example

services:
    scor.twig.controller_action_extension:
        class: Scor\AppBundle\Twig\Extension\ControllerActionExtension
        calls:
            - [setRequest, ["@?request="]]
        tags:
            - { name: twig.extension }
